services:
  db:
    image: postgres
    container_name: lfs_db
    restart: always
    volumes:
      - pgsql:/var/lib/postgresql/data
    env_file:
      - .env-docker

  redis:
    image: redis
    container_name: lfs_redis
    restart: always
    volumes:
      - redis:/var/lib/redis/data

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: lfs_app
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis

volumes:
  pgsql:
  redis: