import os

from app.static.enums import RoleEnum, StationStatusEnum

# SMTP ACCOUNT
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

if SMTP_PASSWORD == "null" or SMTP_USER == "null":
	raise RuntimeError("For testing app, write your SMTP data into .env-docker file")

# USERS PARAMS
USER_DEFAULT_ROLE = RoleEnum.LAUNDRY

# USER AUTHORIZATION PARAMS
ACCESS_TOKEN_EXPIRE_HOURS = 24

# EMAIL VERIFICATION PARAMS
CODE_LENGTH = 6
CODE_EXPIRING_IN_MINUTES = 5

# WASHING MACHINES PARAMS
DEFAULT_WASHING_MACHINES_VOLUME = 10
DEFAULT_WASHING_MACHINES_IS_ACTIVE = True
DEFAULT_WASHING_MACHINES_TRACK_LENGTH = 5.0
MIN_WASHING_MACHINE_VOLUME = 10
MAX_WASHING_MACHINE_VOLUME = 100
MIN_WASHING_MACHINE_TRACK_LENGTH = 1
MAX_WASHING_MACHINE_TRACK_LENGTH = 20

# WASHING AGENTS PARAMS
DEFAULT_WASHING_AGENTS_VOLUME = 25
DEFAULT_WASHING_AGENTS_ROLLBACK = False
MIN_WASHING_AGENTS_VOLUME = 1
MAX_WASHING_AGENTS_VOLUME = 50

# STATIONS PARAMS
DEFAULT_STATION_POWER = True
DEFAULT_STATION_TEH_POWER = True
DEFAULT_STATION_IS_ACTIVE = True
DEFAULT_STATION_WASHING_MACHINES_AMOUNT = 7  # <= MAX_WASHING_MACHINES_AMOUNT
DEFAULT_STATION_WASHING_AGENTS_AMOUNT = 8
DEFAULT_STATION_IS_PROTECTED = False
DEFAULT_STATION_STATUS = StationStatusEnum.AWAITING
MIN_STATION_WASHING_AGENTS_AMOUNT = 1
MIN_STATION_WASHING_MACHINES_AMOUNT = 1
MAX_STATION_WASHING_MACHINES_AMOUNT = 7
MAX_STATION_WASHING_AGENTS_AMOUNT = 8
