"""empty message

Revision ID: 0c5d637a4d88
Revises: 338cd82a95f9
Create Date: 2023-08-29 10:29:13.090050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5d637a4d88'
down_revision = '338cd82a95f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_program', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_program', 'name')
    # ### end Alembic commands ###
