"""empty message

Revision ID: 7298bac13898
Revises: 7b5c954c4ef6
Create Date: 2023-08-03 16:34:15.972499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7298bac13898'
down_revision = '7b5c954c4ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_station_id'), 'station', ['id'], unique=False)
    op.drop_index('ix_station_control_station_id', table_name='station_control')
    op.create_index(op.f('ix_station_control_station_id'), 'station_control', ['station_id'], unique=True)
    op.drop_index('ix_station_settings_station_id', table_name='station_settings')
    op.create_index(op.f('ix_station_settings_station_id'), 'station_settings', ['station_id'], unique=True)
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_station_settings_station_id'), table_name='station_settings')
    op.create_index('ix_station_settings_station_id', 'station_settings', ['station_id'], unique=False)
    op.drop_index(op.f('ix_station_control_station_id'), table_name='station_control')
    op.create_index('ix_station_control_station_id', 'station_control', ['station_id'], unique=False)
    op.drop_index(op.f('ix_station_id'), table_name='station')
    # ### end Alembic commands ###
