"""empty message

Revision ID: 8b3432e596ae
Revises: fd020552cbfd
Create Date: 2023-07-14 18:46:10.480642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3432e596ae'
down_revision = 'fd020552cbfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
